[package]
name = "otpauth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha1_smol = "1.0.0"
url = "2.3.1"
urlencoding = "2.1.2"
serde = { version = "1.0", features = ["derive"] }
